parameters:
  python_version: ''
  architecture: 'x64'
  num_build_jobs: 2

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python_version }}
      architecture: ${{ parameters.architecture }}
      allowUnstable: true

  - bash: |
      echo "##vso[task.setvariable variable=python_version]${{ parameters.python_version }}"
    displayName: 'Set variables'

  - script: |
      python -m pip install -U -r requirements.txt
    displayName: "Install dependencies"

  - script: |
      python -m mypy server
    displayName: 'Run mypy'
    condition: ne(variables['python_version'], '3.6')

  - script: |
      python -m pytest --pyargs server -W error
    displayName: "Run CPU tests"
