name: Test

on: [push, pull_request, workflow_call]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies

      - name: Install python requirements
        run: pip install -r requirements.txt

      - name: Install dev python requirements
        run: pip install -r server/tests/requirements.txt

      - name: Run mypy
        run: mypy server

      - name: Run black
        run: black server --check

      - name: Run pytest
        run: pytest server

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node requirements
        run: npm install

      - name: Run npm linter
        run: npm run lint
